# Generated by Django 4.2.6 on 2023-10-19 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syallabus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='published',
            field=models.DateField(default=datetime.date(2023, 10, 19)),
        ),
    ]
