# Generated by Django 4.2.6 on 2023-10-22 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('syallabus', '0003_books_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=200)),
                ('lastname', models.TextField(max_length=200)),
                ('phone', models.IntegerField(null=True)),
                ('joineddate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
