# Generated by Django 4.2.6 on 2023-10-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syallabus', '0004_member_alter_books_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='joineddate',
        ),
    ]
